### ISSUE TITLE
Rework configuration system using hydra

### ISSUE THREAD

**Issue by jonasteuwen** [directgroup/direct#46]
Using [hydra](https://hydra.cc) rather than OmegaConf will make composition of configurations much more convenient and allow easy access to a lot of hyperparameter search libraries such as Ax Sweeper, nevergrad, and several launcher systems.

For now, this is scheduled for version 1.0 as currently, the configuration system is reasonably stable. Adding more reconstruction algorithms and fixing the open issues is a priority for now.

**Comment by ibro45** [comment]
Commenting to follow how you'll approach Hydra.

Also, you might be interested in how we set up config in midaGAN, especially for Dataset classes (FastMRI and Calgary in your case). As most projects need their own Dataset class that are tailored for the data of the project, it makes sense to have them in the project folder rather than in the framework.

When you specify `project_dir` in the base config ([here](https://github.com/Maastro-CDS-Imaging-Group/midaGAN/blob/90c3302975cd8527407096f84b0728fa45ff330d/midaGAN/conf/base_configs.py#L41)), your run will  [be able to import](https://github.com/Maastro-CDS-Imaging-Group/midaGAN/blob/90c3302975cd8527407096f84b0728fa45ff330d/midaGAN/conf/__init__.py#L36) project-specific classes from the folder. 
Each Dataset class will have its Config class defined at the same location too, as can be seen [here](https://github.com/Maastro-CDS-Imaging-Group/midaGAN/blob/90c3302975cd8527407096f84b0728fa45ff330d/projects/maastro_cbct_to_ct/cbcttoct_dataset.py#L26). At the end, it's initialized [here](https://github.com/Maastro-CDS-Imaging-Group/midaGAN/blob/90c3302975cd8527407096f84b0728fa45ff330d/midaGAN/data/__init__.py#L38).

I think it gives more flexibility and ends up being cleaner too. This supports anything, not Dataset classes only.

**Comment by jonasteuwen** [comment]
Hi, yes, but here projects are specific runs of an algorithm, so there can still be some sharing across projects, suggestions there?
